logging:
    level:
        root: info

spring:
    datasource:
        url: jdbc:h2:mem:db
        username: sa
        password: 
        driverClassName: org.h2.Driver
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
    h2:
        console:
            enabled: true